# Generated by Django 5.0.3 on 2024-04-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_answer_correct_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.CharField(choices=[('i', 'Incorrect'), ('c', 'Correct')], default='i', max_length=1),
        ),
    ]
