# Generated by Django 5.0.3 on 2024-04-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_answerlike_questionlike_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='app.tag'),
        ),
    ]
