# Generated by Django 5.0.3 on 2024-04-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_question_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answers_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='rating',
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(related_name='tags_to_questions', to='app.tag'),
        ),
    ]
