# Generated by Django 5.0.3 on 2024-04-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_answer_rating_remove_question_answers_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.CharField(choices=[('c', 'Correct'), ('i', 'Incorrect')], default='i', max_length=1),
        ),
    ]
